# Flask Specific Configuration
DEBUG = True
CSRF_ENABLED = True
SECRET_KEY = 'UYnHBnJHhnHBmkHJBnMKHBBmHVmnVwEcfR'
# WTF
WTF_CSRF_SECRET_KEY = 'UYnHBnJHhnHBmkHJBnMKHBBmHVmnVwEcfR'
WTF_CSRF_ENABLED = True
WTF_I18N_ENABLED = True
WTF_CSRF_TIME_LIMIT = 3600
WTF_CSRF_SSL_STRICT = True
RECAPTCHA_USE_SSL = True
RECAPTCHA_PUBLIC_KEY = None
RECAPTCHA_PRIVATE_KEY = None
RECAPTCHA_OPTIONS = None
# General
LOGIN_URI = 'https://servicebox.peugeot.com/pages/login.jsp'
LOGIN_ID = 'd259044'
LOGIN_PASS = 'hamer874'
# IMAP SETTINGS
IMAP_GOOGLE_SERVER = 'imap.gmail.com'
IMAP_GOOGLE_SSL_PORT = 993
IMAP_YAHOO_SERVER = 'imap.mail.yahoo.com'
IMAP_YAHOO_SSL_PORT = 993
IMAP_OUTLOOK_SERVER = 'imap-mail.outlook.com'
IMAP_OUTLOOK_SSL_PORT = 993
IMAP_AOL_SERVER = 'imap.aol.com'
IMAP_SSL = True
IMAP_USER = None
IMAP_PASSWORD = None

